#[Venith Toonz]
#name = "Venith Toonz"
#folder = /mnt/adventure_time/
#files = 5
#mode = shuffle
#bump_chance = 0.1
#upnext_enabled = 1
#subtitles = 0

[Veltron Anime]
name = "Veltron Anime"
folder = /mnt/homedata/FOOTAGE/episodes/ANIME/
files = 5
mode = shuffle
bump_chance = 0.1
upnext_enabled = 1
subtitles = 0

#[Venith Programming]
#name = "Venith Programing"
#folder = /mnt/homedata/FOOTAGE/episodes/ANIME/
#files = 5
#mode = shuffle
#bump_chance = 0.1
#upnext_enabled = 1
#subtitles = 0
